# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-16 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import yunity.models.concrete
import yunity.utils.models.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('display_name', models.TextField()),
                ('first_name', yunity.utils.models.field.MaxLengthCharField(max_length=255, null=True)),
                ('last_name', yunity.utils.models.field.MaxLengthCharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', yunity.models.concrete.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', yunity.utils.models.field.MaxLengthCharField(max_length=255, null=True)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('in_conversation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                   to='yunity.Conversation')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
