# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-05 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import yunity.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('yunity', '0003_auto_20151003_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=yunity.models.utils.MaxLengthCharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.TextField(null=True),
        ),
    ]
