# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-18 19:44
from __future__ import unicode_literals

from django.db import migrations
import django_enumfield.db.fields
import yunity.models.concrete


class Migration(migrations.Migration):

    dependencies = [
        ('yunity', '0003_auto_20151117_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=django_enumfield.db.fields.EnumField(default=0, enum=yunity.models.concrete.ConversationType),
        ),
    ]
