# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_store_upcoming_notification_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdate',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickupdate',
            name='is_comment_changed',
            field=models.BooleanField(default=False),
        ),
    ]
