# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_merge_20170815_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='weight',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
