# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0024_auto_20170907_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
