# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_auto_20170908_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
