# Generated by Django 2.0.2 on 2018-03-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupdate',
            name='notifications_sent',
        ),
    ]
