# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 18:14
from __future__ import unicode_literals

import django.utils.timezone
import yunity.base.models
import yunity.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('display_name', models.TextField()),
                ('first_name', yunity.base.models.MaxLengthCharField(max_length=255, null=True)),
                ('last_name', yunity.base.models.MaxLengthCharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', yunity.users.models.UserManager()),
            ],
        ),
    ]
