# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wall',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='walls.Wall'),
        ),
    ]
