# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160728_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_verified',
            field=models.BooleanField(default=False),
        ),
    ]
