# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_group_slack_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
