# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_auto_20170805_1533'),
        ('groups', '0012_group_slack_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conversations.Conversation'),
        ),
    ]
