# Generated by Django 2.0.2 on 2018-03-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_auto_20180309_0936'),
    ]

    operations = [
        migrations.RunSQL(
            sql='create or replace view group_names as select id, name from groups_group',
            reverse_sql='drop view group_names'
        )
    ]
