# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_group_slack_webhook'),
        ('invitations', '0002_auto_20170717_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'group')},
        ),
    ]
