# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 14:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields
import foodsaving.history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0010_auto_20170214_1624'),
        ('stores', '0008_auto_20170220_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('typus', django_enumfield.db.fields.EnumField(default=0,
                                                               enum=foodsaving.history.models.HistoryTypus)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='stores.Store')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
