# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('conversations', '0004_auto_20170805_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
