# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('conversations', '0004_auto_20170805_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('target_type', 'target_id')},
        ),
    ]
