# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_auto_20170806_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='seen_up_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='conversations.ConversationMessage'),
        ),
    ]
