# Generated by Django 2.0.1 on 2018-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_auto_20171207_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
