# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:55
from __future__ import unicode_literals

from django.db import migrations
from django_enumfield import enum


class HistoryTypus(enum.Enum):
    GROUP_CREATE = 0
    GROUP_MODIFY = 1
    GROUP_JOIN = 2
    GROUP_LEAVE = 3
    STORE_CREATE = 4
    STORE_MODIFY = 5
    STORE_DELETE = 6
    PICKUP_CREATE = 7
    PICKUP_MODIFY = 8
    PICKUP_DELETE = 9
    SERIES_CREATE = 10
    SERIES_MODIFY = 11
    SERIES_DELETE = 12
    PICKUP_DONE = 13
    PICKUP_JOIN = 14
    PICKUP_LEAVE = 15
    PICKUP_MISSED = 16


def convert_missed_pickups(apps, schema_editor):
    history_model = apps.get_model('history', 'History')
    to_convert = history_model.objects.filter(typus=HistoryTypus.PICKUP_DONE, users=None)
    print('converting', to_convert.count(), 'history entries')
    to_convert.update(typus=HistoryTypus.PICKUP_MISSED)

    assert history_model.objects.filter(typus=HistoryTypus.PICKUP_DONE, users=None).count() == 0


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20170225_1957'),
    ]

    operations = [
        migrations.RunPython(convert_missed_pickups)
    ]
