# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='wallpost',
            name='wall',
        ),
        migrations.RemoveField(
            model_name='wallpostcontent',
            name='author',
        ),
        migrations.RemoveField(
            model_name='wallpostcontent',
            name='post',
        ),
        migrations.DeleteModel(
            name='Wall',
        ),
        migrations.DeleteModel(
            name='WallPost',
        ),
        migrations.DeleteModel(
            name='WallPostContent',
        ),
    ]
