# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_auto_20170223_1629'),
        ('users', '0013_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
