# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=7),
        ),
    ]
