# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20170219_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
        ),
    ]
