# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 13:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20170219_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
