# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20170220_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='type',
            new_name='typus',
        ),
    ]
