# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161224_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='key_expires',
            new_name='key_expires_at',
        ),
    ]
