# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.Group'),
        ),
    ]
