# Generated by Django 2.0.1 on 2018-01-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_photo'),
        ('userauth', '0003_auto_20180114_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='key_expires_at',
        ),
    ]
