#!/bin/sh

log() {
    /usr/games/cowsay "$@"
}

update_code() {
    local basedir="$1"

    log 'updating code'
    git pull --rebase
    ln -fs "${basedir}/config/local_settings.py.example" \
           "${basedir}/config/local_settings.py"
}

update_dependencies() {
    local basedir="$1"

    log 'updating dependencies'
    . "${basedir}/env/bin/activate"
    pip install -r requirements.pip
}

update_database() {
    local basedir="$1"

    log 'updating database'
    "${basedir}"/manage.py migrate
}

run_tests() {
    local basedir="$1"

    log 'running tests'
    "${basedir}"/manage.py test -v 3
}

main() {
    set -o errexit

    workspace_root="$1"

    update_code "${workspace_root}"
    update_dependencies "${workspace_root}"
    update_database "${workspace_root}"

    run_tests "${workspace_root}"
}

[ $# -eq 1 ] && (cd "$1"; main "$1")
