#!/bin/bash

readonly server_port='8000'
readonly logfile='/tmp/yunity.log'
readonly lockfile='/tmp/yunity.pid'

server_is_down() { [ $(pgrep -c python3) -eq 0 ] && return 0 || return 1; }
kill_server() { pgrep python3 | while read pid; do kill "${pid}"; done; }
run_server() { . env/bin/activate; python3 manage.py runserver 0.0.0.0:${server_port}; }
restart_server() { kill_server && run_server; }
update_server() { (git pull --rebase | grep -q 'Already up-to-date.') && return 1 || return 0; }
log() { echo "$(date) :: $@" >> "${logfile}"; }

main() {
    [ -f "${lockfile}" ] && return || touch "${lockfile}"

    server_is_down \
        && run_server \
        || log 'server is already up -- no need to start it'

    update_server \
        && restart_server \
        || log 'up to date -- keeping server running'

    rm "${lockfile}"
}

[ $# -eq 1 ] && (cd "$1"; main)
