#!/bin/bash

readonly server_port='8000'
readonly logfile='/tmp/yunity.log'

server_is_down() { [ $(pgrep -c python3) -eq 0 ] && return 0 || return 1; }
kill_server() { pgrep python3 | while read pid; do kill "${pid}"; done; }
run_server() { . env/bin/activate; python3 manage.py runserver 0.0.0.0:${server_port}; }
restart_server() { kill_server && run_server; }
update_server() { (git pull --rebase | grep -q 'Already up-to-date.') && return 1 || return 0; }

main() {
    server_is_down \
        && run_server \
        || echo 'server is already up -- no need to start it'

    update_server \
        && restart_server \
        || echo 'up to date -- keeping server running'
}

[ $# -eq 1 ] && (cd "$1"; main >> "${logfile}")
