# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_conversationparticipant_seen_up_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparticipant',
            name='seen_up_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.ConversationMessage'),
        ),
    ]
