# Generated by Django 2.0.2 on 2018-02-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_conversationparticipant_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='received_via',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
