# Generated by Django 2.0.1 on 2018-01-11 11:51
from django.db import migrations
from django.utils import timezone

from foodsaving.userauth.models import VerificationCode as VerificationCodeRecent


def migrate_email_verification_codes(apps, schema_editor):
    User = apps.get_model('users', 'User')
    VerificationCode = apps.get_model('userauth', 'VerificationCode')

    for user in User.objects.all():
        # User.objects.filter() is not applicable here so we have to filter manually:
        if user.activation_key and not user.mail_verified and user.key_expires_at \
                and user.key_expires_at > timezone.now():
            # For simplicity, reset the verification time limit
            VerificationCode.objects.create(user=user,
                                            code=user.activation_key,
                                            type=VerificationCodeRecent.EMAIL_VERIFICATION)


def reverse_migration(apps, schema_editor):
    VerificationCode = apps.get_model('userauth', 'VerificationCode')
    VerificationCode.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_email_verification_codes, reverse_code=reverse_migration),
    ]
