# Generated by Django 2.0.1 on 2018-01-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_import_email_verification_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='invalidated_at',
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='actual verification code'),
        ),
    ]
