# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20170830_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsubscription',
            name='away_at',
            field=models.DateTimeField(null=True),
        ),
    ]
