# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='public_description',
            field=models.TextField(blank=True),
        ),
    ]
