# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 19:38
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_group_public_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Berlin'),
        ),
    ]
