# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 16:24
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_group_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='Europe/Berlin', null=True),
        ),
    ]
