# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_groupmembership_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
