# Generated by Django 2.0.2 on 2018-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_groupmembership_lastseen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
