# Generated by Django 2.0.2 on 2018-03-02 23:09

import django.contrib.postgres.fields
from django.db import migrations, models
import foodsaving.groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_group_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='notification_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=foodsaving.groups.models.get_default_notification_types, size=None),
        ),
    ]
