# Generated by Django 2.0.2 on 2018-03-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_groupmembership_notification_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slack_webhook',
        ),
    ]
