# Generated by Django 2.0.2 on 2018-03-04 13:30

from django.db import migrations


def set_sensible_lastseen_at(apps, schema_editor):
    History = apps.get_model('history', 'History')
    GroupMembership = apps.get_model('groups', 'GroupMembership')
    ConversationMessage = apps.get_model('conversations', 'ConversationMessage')

    for membership in GroupMembership.objects.filter(lastseen_at=None):
        last_history_date = History.objects \
            .filter(users__in=[membership.user]) \
            .order_by('-date') \
            .values_list('date', flat=True).first()

        last_message_date = ConversationMessage.objects \
            .filter(author=membership.user) \
            .order_by('-created_at') \
            .values_list('created_at', flat=True).first()

        membership.lastseen_at = max([date for date in [
            membership.user.created_at,
            last_message_date,
            last_history_date
        ] if date is not None])

        membership.save()


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0022_remove_group_slack_webhook'),
        ('users', '0020_user_mobile_number'),
        ('history', '0004_auto_20170701_1555'),
    ]

    operations = [
        migrations.RunPython(set_sensible_lastseen_at, reverse_code=migrations.RunPython.noop),
    ]
