# Generated by Django 2.0.2 on 2018-03-04 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_set_sensible_lastseen_at_20180304_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='lastseen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
