# Generated by Django 2.0.2 on 2018-03-07 20:51

from django.db import migrations

from foodsaving.groups.models import GroupNotificationType


def subscribe_to_daily_pickup_notifications(apps, schema_editor):
    GroupMembership = apps.get_model('groups', 'GroupMembership')
    for membership in GroupMembership.objects.all():
        if GroupNotificationType.DAILY_PICKUP_NOTIFICATION not in membership.notification_types:
            membership.notification_types.append(GroupNotificationType.DAILY_PICKUP_NOTIFICATION)
            membership.save()


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0024_groupmembership_lastseen_at__required_20180304_1501'),
    ]

    operations = [
        migrations.RunPython(subscribe_to_daily_pickup_notifications, reverse_code=migrations.RunPython.noop),
    ]
