# Generated by Django 2.0.2 on 2018-03-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_subscribe_to_daily_pickup_notifications_20180307_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='inactive_at',
            field=models.DateTimeField(null=True),
        ),
    ]
