# Generated by Django 2.0.2 on 2018-03-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0026_groupmembership_inactive_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='active',
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('playground', 'playground')], default='active', max_length=100),
        ),
    ]
