# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
