# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_auto_20170703_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdateseries',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
