# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_feedback'),
        ('stores', '0016_pickupdate_done_and_processed'),
    ]

    operations = [
    ]
