# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_auto_20170831_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(max_length=100000),
        ),
    ]
