# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_auto_20170831_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
