# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 09:42
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0026_auto_20171027_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='weight',
            field=models.FloatField(blank=True, null=True,
                                    validators=[django.core.validators.MinValueValidator(-0.01),
                                                django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('about', 'given_by')},
        ),
    ]
