# Generated by Django 2.0.2 on 2018-03-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0028_extract_pickups_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='upcoming_notification_hours',
        ),
    ]
