# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django_enumfield.db.fields
import foodsaving.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='platform',
            field=django_enumfield.db.fields.EnumField(default=1, enum=foodsaving.subscriptions.models.PushSubscriptionPlatform),
        ),
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together=set([('user', 'token')]),
        ),
    ]
