steps:
  - name: "Build docker image"
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      # See docs https://woodpecker-ci.org/plugins/Docker%20Buildx
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO}
      registry: codeberg.org
      auto_tag: true
      buildkit_debug: true
      buildkit_driveropt:
        - "image=moby/buildkit:v0.13.1"
      tags: tmp-${CI_COMMIT_SHA:0:8}
      username: ${CI_REPO_OWNER}
      #cache_images:
      #  - codeberg.org/${CI_REPO}:cache
      password:
        from_secret: cb_token
      logins:
        - registry: docker.io
          username: nicksellen
          password:
            from_secret: docker_token

  - name: "Build tar.xz"
    image: "codeberg.org/${CI_REPO}:tmp-${CI_COMMIT_SHA:0:8}"
    secrets:
      - cb_token
    commands:
      - tar czvf /tmp/karrot-frontend.tar.gz -C /usr/share/nginx/html .
      - curl --user nicksellen:$CB_TOKEN --upload-file /tmp/karrot-frontend.tar.gz https://codeberg.org/api/packages/karrot/generic/karrot-frontend/latest/karrot-frontend.tar.gz

when:
  - event: push
    branch: main
  - event: tag
  - event: manual

#depends_on:
#  # Only build if tests pass
#  - test
