when:
  - event: push
    branch: main

depends_on:
  - test

steps:
  - name: "Build latest image"
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO}
      registry: codeberg.org
      auto_tag: false
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      logins:
        - registry: docker.io
          username: nicksellen
          password:
            from_secret: docker_token
      build_args:
        - KARROT_VERSION=latest
        - KARROT_COMMIT=${CI_COMMIT_SHA}
      tags: latest

  - name: "Build tar.gz"
    image: codeberg.org/${CI_REPO}:latest
    environment:
      KARROT_VERSION: latest
      KARROT_COMMIT: ${CI_COMMIT_SHA}
      PACKAGE_BASE: "https://codeberg.org/api/packages/karrot/generic/karrot-frontend"
      PACKAGE_FILENAME: "karrot-frontend.tar.gz"
    secrets:
      - cb_token
    commands:
      - tar czvf "$PACKAGE_FILENAME" -C /usr/share/nginx/html .
      - curl -XDELETE --user "nicksellen:$CB_TOKEN" "$PACKAGE_BASE/$KARROT_VERSION/$PACKAGE_FILENAME" || true
      - curl --user "nicksellen:$CB_TOKEN" --upload-file "$PACKAGE_FILENAME" "$PACKAGE_BASE/$KARROT_VERSION/$PACKAGE_FILENAME"
