when:
  - event: tag

steps:
  - name: "publish tag image"
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: codeberg.org/${CI_REPO}
      registry: codeberg.org
      auto_tag: false
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      logins:
        - registry: docker.io
          username: nicksellen
          password:
            from_secret: docker_token
      build_args:
        - KARROT_VERSION=${CI_COMMIT_TAG}
        - KARROT_COMMIT=${CI_COMMIT_SHA}
      tags: ${CI_COMMIT_TAG}

  - name: "publish tar.gz"
    image: codeberg.org/karrot/plugin-publish-generic-package
    pull: true
    settings:
      image: codeberg.org/${CI_REPO}:latest
      path: /usr/share/nginx/html
      filename: karrot-frontend.tar.gz
      version: ${CI_COMMIT_TAG}
      registry: codeberg.org
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
