#!/bin/bash

### webcam snapshot (begin) ###

webcam_snapshot() {
    local snapshot_location="${HOME}/Pictures/git"
    local snapshot_prefix="$(git config --get 'user.email')-$(date +'%Y%m%d_%H%M%S')"
    local snapshot_remote='ftp://anonymous@192.168.1.63/git-commit-images/'
    local snapshot_path="${snapshot_location}/${snapshot_prefix}00001"

    mkdir -p "${snapshot_location}"
    fswebcam -r 640x480 --jpeg 85 -D 0 "${snapshot_path}.jpg"
    curl -T "${snapshot_path}.jpg" "${snapshot_remote}"
}

webcam_snapshot &

### webcam snapshot (end)  ###
