#!/bin/bash

### webcam snapshot (begin) ###

webcam_snapshot() {
    local snapshot_location="${HOME}/Pictures/git"
    local snapshot_prefix="$(git config --get 'user.email')-$(date +'%Y%m%d_%H%M%S')"
    local snapshot_remote='ftp://anonymous@192.168.1.63/git-commit-images/'
    local snapshot_path="${snapshot_location}/${snapshot_prefix}00001"

    mkdir -p "${snapshot_location}"
    vlc --quiet -I dummy v4l2:///dev/video0 --video-filter scene --no-audio \
        --scene-path "${snapshot_location}" --scene-prefix "${snapshot_prefix}" \
        --scene-format 'png' vlc://quit --run-time=1 -V dummy -A dummy
    convert "${snapshot_path}.png" "${snapshot_path}.jpg" && rm "${snapshot_path}.png"
    curl -T "${snapshot_path}.jpg" "${snapshot_remote}"
}

webcam_snapshot &

### webcam snapshot (end)  ###
