# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20160728_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='groups.Group'),
        ),
    ]
