# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20170201_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupdate',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_dates', to='stores.PickupDateSeries'),
        ),
    ]
