# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20170204_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupdate',
            name='max_collectors',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
