# Generated by Django 2.0.2 on 2018-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailevent',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
